name: Deploy

on:
  push:
    branches: [ main ]

jobs:

  # Continuous Deployment to Fly.io
  # https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: [build]
    # https://stackoverflow.com/questions/58139406/only-run-job-on-specific-branch-with-github-actions
    if: github.ref == 'refs/heads/main'
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.1
        with:
          args: "deploy"